version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=rdependencies
      - POSTGRES_USER=rdependencies
      - POSTGRES_DB=rdependencies
